// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/audio.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SymphoniaDecoder {
  const SymphoniaDecoder.raw();

  Audio decode({required String format, required List<int> data}) => RustLib
      .instance
      .api
      .crateApiDecoderSymphoniaDecoderSymphoniaDecoderDecode(
        that: this,
        format: format,
        data: data,
      );

  factory SymphoniaDecoder() =>
      RustLib.instance.api.crateApiDecoderSymphoniaDecoderSymphoniaDecoderNew();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SymphoniaDecoder && runtimeType == other.runtimeType;
}
