// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/chart.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `record_update_interval`

class StreamCommunicator {
  const StreamCommunicator.raw();

  void addChart({required String key, required Chart chart}) => RustLib
      .instance
      .api
      .crateApiCommunicatorCommunicatorStreamCommunicatorAddChart(
        that: this,
        key: key,
        chart: chart,
      );

  factory StreamCommunicator() => RustLib.instance.api
      .crateApiCommunicatorCommunicatorStreamCommunicatorNew();

  void removeAllCharts() => RustLib.instance.api
      .crateApiCommunicatorCommunicatorStreamCommunicatorRemoveAllCharts(
        that: this,
      );

  void removeChart({required String key, required DataType dataType}) => RustLib
      .instance
      .api
      .crateApiCommunicatorCommunicatorStreamCommunicatorRemoveChart(
        that: this,
        key: key,
        dataType: dataType,
      );

  void updateAllCharts({required List<ChartWIthKey> charts}) => RustLib
      .instance
      .api
      .crateApiCommunicatorCommunicatorStreamCommunicatorUpdateAllCharts(
        that: this,
        charts: charts,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamCommunicator && runtimeType == other.runtimeType;
}
