// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_processor.dart';
import 'api/simple.dart';
import 'api/util.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 680387333;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_vad',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAudioProcessorAudioProcessorAdd({
    required AudioProcessor that,
    required String filePath,
    required List<int> fileData,
  });

  BigInt crateApiAudioProcessorAudioProcessorAudioDataLen({
    required AudioProcessor that,
    required String filePath,
  });

  Future<ChartData> crateApiAudioProcessorAudioProcessorGetAudioData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  });

  Future<ChartData> crateApiAudioProcessorAudioProcessorGetDownSampledData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
    required double downSampleFactor,
  });

  Future<ChartData> crateApiAudioProcessorAudioProcessorGetFftData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  });

  BigInt crateApiAudioProcessorAudioProcessorGetFrameSize({
    required AudioProcessor that,
    required String filePath,
  });

  int crateApiAudioProcessorAudioProcessorGetSampleRate({
    required AudioProcessor that,
    required String filePath,
  });

  Future<AudioProcessor> crateApiAudioProcessorAudioProcessorNew();

  void crateApiAudioProcessorAudioProcessorSetFrameSize({
    required AudioProcessor that,
    required BigInt frameSize,
  });

  Future<Float64List> crateApiUtilCalculateFftParallel({
    required List<double> inputData,
    required BigInt frameSize,
  });

  Future<ChartData> crateApiUtilDownSampleData({
    required ChartData rawData,
    required double downSampleFactor,
  });

  String crateApiSimpleGreet({required String name});

  void crateApiSimpleInitApp();

  Future<Float64List> crateApiUtilPerformLog10Parallel({
    required List<double> inputData,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioProcessor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioProcessor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioProcessorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAudioProcessorAudioProcessorAdd({
    required AudioProcessor that,
    required String filePath,
    required List<int> fileData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_list_prim_u_8_loose(fileData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorAddConstMeta,
        argValues: [that, filePath, fileData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorAudioProcessorAddConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_add",
        argNames: ["that", "filePath", "fileData"],
      );

  @override
  BigInt crateApiAudioProcessorAudioProcessorAudioDataLen({
    required AudioProcessor that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorAudioDataLenConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorAudioDataLenConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_audio_data_len",
        argNames: ["that", "filePath"],
      );

  @override
  Future<ChartData> crateApiAudioProcessorAudioProcessorGetAudioData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_box_autoadd_record_f_64_f_64(offset, serializer);
          sse_encode_box_autoadd_record_usize_usize(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chart_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorGetAudioDataConstMeta,
        argValues: [that, filePath, offset, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorGetAudioDataConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_get_audio_data",
        argNames: ["that", "filePath", "offset", "index"],
      );

  @override
  Future<ChartData> crateApiAudioProcessorAudioProcessorGetDownSampledData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
    required double downSampleFactor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_box_autoadd_record_f_64_f_64(offset, serializer);
          sse_encode_box_autoadd_record_usize_usize(index, serializer);
          sse_encode_f_64(downSampleFactor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chart_data,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioProcessorAudioProcessorGetDownSampledDataConstMeta,
        argValues: [that, filePath, offset, index, downSampleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorGetDownSampledDataConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_get_down_sampled_data",
        argNames: ["that", "filePath", "offset", "index", "downSampleFactor"],
      );

  @override
  Future<ChartData> crateApiAudioProcessorAudioProcessorGetFftData({
    required AudioProcessor that,
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_box_autoadd_record_f_64_f_64(offset, serializer);
          sse_encode_box_autoadd_record_usize_usize(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chart_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorGetFftDataConstMeta,
        argValues: [that, filePath, offset, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorAudioProcessorGetFftDataConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_get_fft_data",
        argNames: ["that", "filePath", "offset", "index"],
      );

  @override
  BigInt crateApiAudioProcessorAudioProcessorGetFrameSize({
    required AudioProcessor that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorGetFrameSizeConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorGetFrameSizeConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_get_frame_size",
        argNames: ["that", "filePath"],
      );

  @override
  int crateApiAudioProcessorAudioProcessorGetSampleRate({
    required AudioProcessor that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorGetSampleRateConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorGetSampleRateConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_get_sample_rate",
        argNames: ["that", "filePath"],
      );

  @override
  Future<AudioProcessor> crateApiAudioProcessorAudioProcessorNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorAudioProcessorNewConstMeta =>
      const TaskConstMeta(debugName: "AudioProcessor_new", argNames: []);

  @override
  void crateApiAudioProcessorAudioProcessorSetFrameSize({
    required AudioProcessor that,
    required BigInt frameSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
            that,
            serializer,
          );
          sse_encode_usize(frameSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAudioProcessorSetFrameSizeConstMeta,
        argValues: [that, frameSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioProcessorAudioProcessorSetFrameSizeConstMeta =>
      const TaskConstMeta(
        debugName: "AudioProcessor_set_frame_size",
        argNames: ["that", "frameSize"],
      );

  @override
  Future<Float64List> crateApiUtilCalculateFftParallel({
    required List<double> inputData,
    required BigInt frameSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(inputData, serializer);
          sse_encode_usize(frameSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilCalculateFftParallelConstMeta,
        argValues: [inputData, frameSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilCalculateFftParallelConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_fft_parallel",
        argNames: ["inputData", "frameSize"],
      );

  @override
  Future<ChartData> crateApiUtilDownSampleData({
    required ChartData rawData,
    required double downSampleFactor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_chart_data(rawData, serializer);
          sse_encode_f_64(downSampleFactor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chart_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilDownSampleDataConstMeta,
        argValues: [rawData, downSampleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilDownSampleDataConstMeta => const TaskConstMeta(
    debugName: "down_sample_data",
    argNames: ["rawData", "downSampleFactor"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  void crateApiSimpleInitApp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Float64List> crateApiUtilPerformLog10Parallel({
    required List<double> inputData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(inputData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilPerformLog10ParallelConstMeta,
        argValues: [inputData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilPerformLog10ParallelConstMeta =>
      const TaskConstMeta(
        debugName: "perform_log10_parallel",
        argNames: ["inputData"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioProcessor => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioProcessor => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor;

  @protected
  AudioProcessor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioProcessor
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioProcessor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioProcessor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ChartData dco_decode_box_autoadd_chart_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chart_data(raw);
  }

  @protected
  (double, double) dco_decode_box_autoadd_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (double, double);
  }

  @protected
  (BigInt, BigInt) dco_decode_box_autoadd_record_usize_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (BigInt, BigInt);
  }

  @protected
  ChartData dco_decode_chart_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChartData(
      index: dco_decode_list_prim_f_64_strict(arr[0]),
      data: dco_decode_list_prim_f_64_strict(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_f_64(arr[1]));
  }

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_usize(arr[0]), dco_decode_usize(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AudioProcessor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioProcessor
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioProcessor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioProcessor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioProcessorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ChartData sse_decode_box_autoadd_chart_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chart_data(deserializer));
  }

  @protected
  (double, double) sse_decode_box_autoadd_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_f_64_f_64(deserializer));
  }

  @protected
  (BigInt, BigInt) sse_decode_box_autoadd_record_usize_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_usize_usize(deserializer));
  }

  @protected
  ChartData sse_decode_chart_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_list_prim_f_64_strict(deserializer);
    var var_data = sse_decode_list_prim_f_64_strict(deserializer);
    return ChartData(index: var_index, data: var_data);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_usize(deserializer);
    var var_field1 = sse_decode_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    AudioProcessor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioProcessorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    AudioProcessor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioProcessorImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    AudioProcessor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioProcessorImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioProcessor(
    AudioProcessor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioProcessorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_chart_data(
    ChartData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chart_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_f_64_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_usize_usize(self, serializer);
  }

  @protected
  void sse_encode_chart_data(ChartData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.index, serializer);
    sse_encode_list_prim_f_64_strict(self.data, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(
      self is Float64List ? self : Float64List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.$1, serializer);
    sse_encode_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AudioProcessorImpl extends RustOpaque implements AudioProcessor {
  // Not to be used by end users
  AudioProcessorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioProcessorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioProcessor,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioProcessor,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioProcessorPtr,
  );

  Future<void> add({required String filePath, required List<int> fileData}) =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorAdd(
        that: this,
        filePath: filePath,
        fileData: fileData,
      );

  BigInt audioDataLen({required String filePath}) =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorAudioDataLen(
        that: this,
        filePath: filePath,
      );

  Future<ChartData> getAudioData({
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  }) => RustLib.instance.api.crateApiAudioProcessorAudioProcessorGetAudioData(
    that: this,
    filePath: filePath,
    offset: offset,
    index: index,
  );

  Future<ChartData> getDownSampledData({
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
    required double downSampleFactor,
  }) => RustLib.instance.api
      .crateApiAudioProcessorAudioProcessorGetDownSampledData(
        that: this,
        filePath: filePath,
        offset: offset,
        index: index,
        downSampleFactor: downSampleFactor,
      );

  Future<ChartData> getFftData({
    required String filePath,
    required (double, double) offset,
    required (BigInt, BigInt) index,
  }) => RustLib.instance.api.crateApiAudioProcessorAudioProcessorGetFftData(
    that: this,
    filePath: filePath,
    offset: offset,
    index: index,
  );

  BigInt getFrameSize({required String filePath}) =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorGetFrameSize(
        that: this,
        filePath: filePath,
      );

  int getSampleRate({required String filePath}) =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorGetSampleRate(
        that: this,
        filePath: filePath,
      );

  void setFrameSize({required BigInt frameSize}) =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorSetFrameSize(
        that: this,
        frameSize: frameSize,
      );
}
