// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../traits/audio_storage.dart';
import '../types/audio.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KvAudioStorage>>
abstract class KvAudioStorage implements RustOpaqueInterface, AudioStorage {
  @override
  Future<Audio> load({required String key});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<KvAudioStorage> newInstance() =>
      RustLib.instance.api.crateApiStorageKvAudioStorageKvAudioStorageNew();

  @override
  Future<void> remove({required String key});

  @override
  Future<void> save({required String key, required Audio storageUnit});
}
