// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../traits/cached_chart_storage.dart';
import '../types/chart.dart';
import '../types/config.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KvCachedChartStorage>>
abstract class KvCachedChartStorage
    implements RustOpaqueInterface, CachedChartStorage {
  @override
  void add({required String key, required Chart chart});

  Config get config;

  set config(Config config);

  @override
  Chart get_({required String key});

  factory KvCachedChartStorage() => RustLib.instance.api
      .crateApiStorageKvCachedChartStorageKvCachedChartStorageNew();

  @override
  void remove({required String key, required DataType dataType});
}
