// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/audio.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

abstract class AudioStorage {
  Future<Audio> load({required String key});

  Future<void> remove({required String key});

  Future<void> save({required String key, required Audio storageUnit});
}
