// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/chart.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

abstract class CachedChartStorage {
  void add({required String key, required Chart chart});

  Chart get_({required String key, required DataType dataType});

  List<ChartWIthKey> getAllCache();

  void remove({required String key, required DataType dataType});
}
