// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/vad.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

abstract class VadAlgorithm {
  /// Human-readable display name (e.g. "Energy-based VAD").
  Future<void> displayName();

  /// Returns the current parameters with their metadata (min/max/step).
  Future<List<VadParamDef>> getParameters();

  /// Unique short name (e.g. "energy", "zcr").
  Future<void> name();

  /// Run VAD on raw PCM samples, returning per-frame confidence scores.
  Future<VadResult> process({
    required List<double> samples,
    required int sampleRate,
  });

  /// Updates one parameter by key. Value is f32 for simplicity
  /// (bool params: 0.0/1.0, int params cast from f32).
  Future<void> updateParameter({required String key, required double value});
}
