// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/chart.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EqualStep {
  const EqualStep();

  Chart downSample({required Chart chart, required BigInt targetPointsNum}) =>
      RustLib.instance.api.crateApiSamplingEqualStepEqualStepDownSample(
        that: this,
        chart: chart,
        targetPointsNum: targetPointsNum,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualStep && runtimeType == other.runtimeType;
}
