// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Audio>>
abstract class Audio implements RustOpaqueInterface {
  AudioData get data;

  AudioInfo get info;

  set data(AudioData data);

  set info(AudioInfo info);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioData>>
abstract class AudioData implements RustOpaqueInterface {
  ArcVecF32 get samples;

  set samples(ArcVecF32 samples);
}

class AudioInfo {
  final int sampleRate;

  const AudioInfo({required this.sampleRate});

  @override
  int get hashCode => sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInfo &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate;
}
