// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`

@freezed
sealed class AppError with _$AppError implements FrbException {
  const AppError._();

  const factory AppError.io(String field0) = AppError_Io;
  const factory AppError.format(String field0) = AppError_Format;
  const factory AppError.decode(String field0) = AppError_Decode;
  const factory AppError.storage(String field0) = AppError_Storage;
  const factory AppError.cache(String field0) = AppError_Cache;
  const factory AppError.notFound(String field0) = AppError_NotFound;
  const factory AppError.generic(String field0) = AppError_Generic;
  const factory AppError.processingError(String field0) =
      AppError_ProcessingError;
  const factory AppError.invalidChartName(String field0) =
      AppError_InvalidChartName;
}
