// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `bool_`, `float`, `int`

class VadParamDef {
  final String key;
  final String label;
  final String kind;
  final double value;
  final double min;
  final double max;
  final double step;

  const VadParamDef({
    required this.key,
    required this.label,
    required this.kind,
    required this.value,
    required this.min,
    required this.max,
    required this.step,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      kind.hashCode ^
      value.hashCode ^
      min.hashCode ^
      max.hashCode ^
      step.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VadParamDef &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          kind == other.kind &&
          value == other.value &&
          min == other.min &&
          max == other.max &&
          step == other.step;
}

class VadResult {
  final Float32List confidence;
  final int frameSize;

  const VadResult({required this.confidence, required this.frameSize});

  @override
  int get hashCode => confidence.hashCode ^ frameSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VadResult &&
          runtimeType == other.runtimeType &&
          confidence == other.confidence &&
          frameSize == other.frameSize;
}
