[package]
name = "rust_lib_vad"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O3",
    "--enable-bulk-memory",
    "--enable-threads",
    "--enable-mutable-globals",
    "--enable-nontrapping-float-to-int",
    "--enable-simd",
]

[dependencies]
flutter_rust_bridge = "=2.12.0"
num-complex = "0.4.6"
rayon = "1.11.0"
rustfft = "6.4.1"
symphonia = { version = "0.6.0", features = ["all"] }
dashmap = { version = "6.2.1", features = ["rayon"] }
log = "0.4.30"
android_logger = "0.15.1"
env_logger = "0.11.10"
ctor = "1.0.7"
thiserror = "2.0.18"
console_log = { version = "1.0", optional = false }
console_error_panic_hook = { version = "0.1.7", optional = false }
burn = { version = "0.21.0", default-features = false, features = ["flex"] }
burn-flex = "0.21.0"
burn-store = { version = "0.21.0", features = ["burnpack"] }
cpal = "0.17.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.17.3", features = ["wasm-bindgen"] }

[build-dependencies]
burn-onnx = "0.21.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
