// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioProcessor>>
abstract class AudioProcessor implements RustOpaqueInterface {
  static Future<Float64List> fft() =>
      RustLib.instance.api.crateApiAudioProcessorAudioProcessorFft();

  Future<Float64List> getAudioData();

  void getFilePath();

  BigInt getFrameSize();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioProcessor> newInstance({
    required String filePath,
    required List<int> fileData,
  }) => RustLib.instance.api.crateApiAudioProcessorAudioProcessorNew(
    filePath: filePath,
    fileData: fileData,
  );

  void setFrameSize({required BigInt frameSize});
}
