// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types/audio.dart';

// These functions are ignored because they are not marked as `pub`: `fill_buffer`, `start_stream`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayerCommand`, `SharedState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Player>>
abstract class Player implements RustOpaqueInterface {
  Future<double> durationSecs();

  Future<bool> isPlaying();

  Future<void> load({required Audio audio});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Player> newInstance() =>
      RustLib.instance.api.crateApiPlayerPlayerNew();

  Future<void> pause();

  Future<void> play({required BigInt startSample});

  Future<double> positionFraction();

  Future<double> positionSecs();

  Future<void> seek({required BigInt sample});

  Future<void> setSpeed({required double multiplier});

  Future<void> stop();

  Future<BigInt?> totalSamples();
}

class PlaybackState {
  final bool isPlaying;
  final double position;
  final double duration;

  const PlaybackState({
    required this.isPlaying,
    required this.position,
    required this.duration,
  });

  @override
  int get hashCode =>
      isPlaying.hashCode ^ position.hashCode ^ duration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          isPlaying == other.isPlaying &&
          position == other.position &&
          duration == other.duration;
}
