// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<Float64List> calculateFftParallel({
  required List<double> inputData,
  required BigInt frameSize,
}) => RustLib.instance.api.crateApiUtilCalculateFftParallel(
  inputData: inputData,
  frameSize: frameSize,
);

Future<Float64List> performLog10Parallel({required List<double> inputData}) =>
    RustLib.instance.api.crateApiUtilPerformLog10Parallel(inputData: inputData);

Future<ChartData> downSampleData({
  required ChartData rawData,
  required double downSampleFactor,
}) => RustLib.instance.api.crateApiUtilDownSampleData(
  rawData: rawData,
  downSampleFactor: downSampleFactor,
);

class ChartData {
  final Float64List index;
  final Float64List data;

  const ChartData({required this.index, required this.data});

  @override
  int get hashCode => index.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartData &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          data == other.data;
}
