// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Float64List> caculateFftParallel({
  required List<double> inputData,
  required BigInt frameSize,
}) => RustLib.instance.api.crateApiUtilCaculateFftParallel(
  inputData: inputData,
  frameSize: frameSize,
);

Future<DownSampleChartData> downSampleData({required List<double> rawData}) =>
    RustLib.instance.api.crateApiUtilDownSampleData(rawData: rawData);

class DownSampleChartData {
  final Float64List index;
  final Float64List data;

  const DownSampleChartData({required this.index, required this.data});

  @override
  int get hashCode => index.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownSampleChartData &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          data == other.data;
}
