// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types/vad.dart';

// These functions are ignored because they are not marked as `pub`: `create_vad`, `vad_lock`

Future<List<String>> listAlgorithmNames() =>
    RustLib.instance.api.crateApiVadListAlgorithmNames();

Future<String> currentAlgorithmName() =>
    RustLib.instance.api.crateApiVadCurrentAlgorithmName();

Future<void> setAlgorithm({required String name}) =>
    RustLib.instance.api.crateApiVadSetAlgorithm(name: name);

Future<List<VadParamDef>> getParameters() =>
    RustLib.instance.api.crateApiVadGetParameters();

Future<void> setParameter({required String key, required double value}) =>
    RustLib.instance.api.crateApiVadSetParameter(key: key, value: value);

Future<VadResult> process({
  required List<double> samples,
  required int sampleRate,
}) => RustLib.instance.api.crateApiVadProcess(
  samples: samples,
  sampleRate: sampleRate,
);
