// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types/vad.dart';

// These functions are ignored because they are not marked as `pub`: `create`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VadEngine>>
abstract class VadEngine implements RustOpaqueInterface {
  Future<String> currentName();

  Future<List<VadParamDef>> getParameters();

  Future<List<String>> listAlgorithms();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VadEngine> newInstance({required String name}) =>
      RustLib.instance.api.crateApiVadVadEngineNew(name: name);

  Future<VadResult> process({
    required List<double> samples,
    required int sampleRate,
  });

  Future<void> setAlgorithm({required String name});

  Future<void> setParameter({required String key, required double value});
}
