// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/audio.dart';
import '../types/chart.dart';
import '../types/config.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EnergyCalculator {
  const EnergyCalculator();

  Chart transform({required Audio data, required Config config}) =>
      RustLib.instance.api.crateApiTransformEnergyEnergyCalculatorTransform(
        that: this,
        data: data,
        config: config,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnergyCalculator && runtimeType == other.runtimeType;
}
