// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/chart.dart';
import '../types/config.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

AudioProcessorEngine createDefaultEngine({required Config config}) =>
    RustLib.instance.api.crateApiCoreEngineCreateDefaultEngine(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioProcessorEngine>>
abstract class AudioProcessorEngine implements RustOpaqueInterface {
  void add({required String filePath, required List<int> audioData});

  factory AudioProcessorEngine({
    required Config config,
    required BoxAudioDecoder decoder,
    required BoxAudioStorage storage,
    required BoxCachedChartStorage cache,
  }) => RustLib.instance.api.crateApiCoreEngineAudioProcessorEngineNew(
    config: config,
    decoder: decoder,
    storage: storage,
    cache: cache,
  );

  void removeAudio({required String filePath});

  void removeChart({required String filePath, required DataType dataType});

  void setDownSamplePointsNum({required BigInt pointsNum});

  void setIndexRange({required double start, required double end});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn AudioDecoder + Send + Sync >>>
abstract class BoxAudioDecoder implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn AudioStorage + Send + Sync >>>
abstract class BoxAudioStorage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn CachedChartStorage + Send + Sync >>>
abstract class BoxCachedChartStorage implements RustOpaqueInterface {}
