// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../types/chart.dart';
import '../types/config.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `update_all`, `update_max_index`

Future<AudioProcessorEngine> createDefaultEngine({required Config config}) =>
    RustLib.instance.api.crateApiCoreEngineCreateDefaultEngine(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioProcessorEngine>>
abstract class AudioProcessorEngine implements RustOpaqueInterface {
  Future<void> add({
    required String filePath,
    required String format,
    required List<int> audioData,
  });

  Future<void> addChart({required String filePath, required DataType dataType});

  Future<double> getMaxIndex();

  Future<(double, double)> getYRange();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioProcessorEngine> newInstance({
    required Config config,
    required BoxAudioDecoder decoder,
    required BoxAudioStorage storage,
    required BoxCachedChartStorage cache,
    required BoxCommunicator communicator,
  }) => RustLib.instance.api.crateApiCoreEngineAudioProcessorEngineNew(
    config: config,
    decoder: decoder,
    storage: storage,
    cache: cache,
    communicator: communicator,
  );

  Future<void> removeAudio({required String filePath});

  Future<void> removeChart({
    required String filePath,
    required DataType dataType,
  });

  Future<void> reserveVisible({required String chartName});

  Future<void> setConfig({required Config config});

  Future<void> setDownSamplePointsNum({required BigInt pointsNum});

  Future<void> setIndexRange({required double start, required double end});

  Future<void> setSelectedAudio({String? chartName});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn AudioDecoder + Send + Sync >>>
abstract class BoxAudioDecoder implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn AudioStorage + Send + Sync >>>
abstract class BoxAudioStorage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn CachedChartStorage + Send + Sync >>>
abstract class BoxCachedChartStorage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn Communicator + Send + Sync >>>
abstract class BoxCommunicator implements RustOpaqueInterface {}
